language: ruby
sudo: false
before_install: gem install bundler -v 1.10.6
script: bundle exec rspec
cache: bundler
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0 # EOL SOON

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
