language: ruby
sudo: required
services:
  - docker

before_install:
  - env
  - docker build

script: docker run -it `docker build -q .` rspec
cache: bundler

addons:
  code_climate:
    repo_token: a91a047fa77c9b56bbd07cdd5ecddc3877515d8193adb6047eb67344d17580af
