language: ruby
sudo: false
before_install: gem install bundler -v 1.10.6
script: bundle exec rspec
cache: bundler

addons:
  code_climate:
    repo_token: a91a047fa77c9b56bbd07cdd5ecddc3877515d8193adb6047eb67344d17580af
